"""Add VAD to MusicVibeCache

Revision ID: 2051721b9f4d
Revises: b32af39acf33
Create Date: 2026-03-05 16:46:50.092283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2051721b9f4d'
down_revision: Union[str, Sequence[str], None] = 'b32af39acf33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_vibe_cache', sa.Column('valence', sa.JSON(), nullable=True))
    op.add_column('music_vibe_cache', sa.Column('arousal', sa.JSON(), nullable=True))
    op.add_column('music_vibe_cache', sa.Column('dominance', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music_vibe_cache', 'dominance')
    op.drop_column('music_vibe_cache', 'arousal')
    op.drop_column('music_vibe_cache', 'valence')
    # ### end Alembic commands ###
