"""add_health_snapshot_table_and_user_biometrics

Revision ID: 28776b0b6bb3
Revises: 3a2b1c4d5e6f
Create Date: 2026-03-13 10:42:06.376696

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '28776b0b6bb3'
down_revision: Union[str, Sequence[str], None] = '3a2b1c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('readiness', sa.String(), nullable=True),
    sa.Column('heart_rate', sa.JSON(), nullable=True),
    sa.Column('hrv', sa.JSON(), nullable=True),
    sa.Column('sleep', sa.JSON(), nullable=True),
    sa.Column('steps_today', sa.Integer(), nullable=True),
    sa.Column('active_energy_kcal', sa.Float(), nullable=True),
    sa.Column('last_workout', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_snapshots_id'), 'health_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_health_snapshots_user_id'), 'health_snapshots', ['user_id'], unique=False)
    op.add_column('users', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('height_cm', sa.Float(), nullable=True))
    op.alter_column('users', 'needs_loop_recalc',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'needs_loop_recalc',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('users', 'height_cm')
    op.drop_column('users', 'weight_kg')
    op.drop_index(op.f('ix_health_snapshots_user_id'), table_name='health_snapshots')
    op.drop_index(op.f('ix_health_snapshots_id'), table_name='health_snapshots')
    op.drop_table('health_snapshots')
    # ### end Alembic commands ###
