"""Add episodic memory table

Revision ID: b3e576732fd9
Revises: ee1122334455
Create Date: 2026-03-16 17:17:40.660545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'b3e576732fd9'
down_revision: Union[str, Sequence[str], None] = 'ee1122334455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodic_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_episodic_mem_vec', 'episodic_memories', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_l2_ops'})
    op.create_index(op.f('ix_episodic_memories_id'), 'episodic_memories', ['id'], unique=False)
    op.create_index(op.f('ix_episodic_memories_user_id'), 'episodic_memories', ['user_id'], unique=False)
    op.create_index('idx_health_snapshot_dedup', 'health_snapshots', ['user_id', 'fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_health_snapshot_dedup', table_name='health_snapshots')
    op.drop_index(op.f('ix_episodic_memories_user_id'), table_name='episodic_memories')
    op.drop_index(op.f('ix_episodic_memories_id'), table_name='episodic_memories')
    op.drop_index('idx_episodic_mem_vec', table_name='episodic_memories', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_l2_ops'})
    op.drop_table('episodic_memories')
    # ### end Alembic commands ###
