name: Deploy to Server

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
            cd backend
            # This securely writes the multiline secret exactly as you pasted it in GitHub
            cat << 'EOF' > .env
            ${{ secrets.ENV_FILE_CONTENT }}
            EOF

      - name: Deploy with Docker Compose
        run: |
          cd backend
          echo "Rebuilding and restarting backend..."
          # Notice we removed "sudo" from the next two lines
          docker compose up -d --build --no-deps braindump-backend
          
          echo "Cleaning up old images..."
          docker image prune -f
          
          echo "Deployment complete!"
